Add bjet counters, update PATObjectCounter
nwoods/UWVV pull request #8
Opened 2016-09-17 09:56 UTC by kdlong

Added counters for number of jets passing various b-jet criteria. Also modified PATObjectCounter to take a list of labels and collections since loading the collection and counting for a single ID is inefficient when checking one collection with multiple IDs. Updated WZLeptonCounters and ZZLeptonCounters to work with this change. 

@nwoods , can you check that this didn't change the behavior of counters for your IDs? It really shouldn't unless I made a dumb mistake.

2016-09-17 09:58 UTC, kdlong commented
Also added a check in PATObjectCounter to return src.size() if cut =="". Should now be more efficient, and nJets could be removed from the function library and counted in this way instead.

2016-09-20 12:10 UTC, nwoods commented on AnalysisTools/python/templates/BJetCounters.py
> +            for chan in parseChannels('zl'):
It occurs to me that we should probably just make `AnalysisFlow*` objects channel aware (just take the channel(s) as the first non-self argument to `__init__()`) so we don't have to put them in by hand every time. No need to rush to it now, but it should probably be on our collective to-do list.

2016-09-20 12:16 UTC, nwoods requested changes
Looks good, thanks! Just one quick change (noted inline) and I'm happy.

2016-09-20 12:16 UTC, nwoods commented on AnalysisTools/plugins/PATObjectCounter.cc
> +          StringCutObjectSelector<T> cut(cuts_[i]);
I think this needs to be moved back to the constructor. IIRC, the string cut object selectors use some kind of JIT compilation that I expect to be slow to initialize but fast to run later.

2016-09-21 12:33 UTC, nwoods approved these changes

2016-09-21 12:34 UTC, nwoods commented on AnalysisTools/plugins/PATObjectCounter.cc
> +  std::vector<StringCutObjectSelector<T>> cuts_;
It may not ever matter, but we might want to use `StringCutObjectSelector<T,true>`, just for robustness.

2016-09-21 12:35 UTC, nwoods commented on AnalysisTools/plugins/PATObjectCounter.cc
> +  const std::vector<std::string> cut_strings_;
With apologies for being obnoxiously picky, could we put this variable in camelCase like everything else?

2016-09-21 13:09 UTC, kdlong commented
I'll agree to this if I can start using my usual tab style 😏

On Wed, Sep 21, 2016 at 2:45 PM, Nate Woods <notifications@github.com>
wrote:

> *@nwoods* commented on this pull request.
> ------------------------------
>
> In AnalysisTools/plugins/PATObjectCounter.cc
> <https://github.com/nwoods/UWVV/pull/8#pullrequestreview-940447>:
>
> >    const std::vector<std::string> labels_;
> +  std::vector<StringCutObjectSelector<T>> cuts_;
>
> It may not ever matter, but we might want to use
> StringCutObjectSelector<T,true>, just for robustness.
> ------------------------------
>
> In AnalysisTools/plugins/PATObjectCounter.cc
> <https://github.com/nwoods/UWVV/pull/8#pullrequestreview-940447>:
>
> > @@ -43,32 +43,36 @@ class PATObjectCounter : public edm::stream::EDProducer<>
>    virtual void produce(edm::Event& iEvent, const edm::EventSetup& iSetup);
>
>    const edm::EDGetTokenT<edm::View<T> > srcToken_;
> -  const std::vector<std::string> cuts_;
> +  const std::vector<std::string> cut_strings_;
>
> With apologies for being obnoxiously picky, could we put this variable in
> camelCase like everything else?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/nwoods/UWVV/pull/8#pullrequestreview-940447>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AGYm8G2x9lewi1opsTpsFrxgRen1ah9Pks5qsSb7gaJpZM4J_jyn>
> .
>

2016-09-27 09:39 UTC, merged